version: "3.7"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: 'Asia/Hong_Kong'
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  postgresql:
    image: "bitnami/postgresql:13"
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRES_PASSWORD=eigen3m!
    volumes:
      - "./postgresql:/bitnami/postgresql"
    ports:
      - "5433:5432" 